// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvbhqtohkijtkovqlsog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2YmhxdG9oa2lqdGtvdnFsc29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMDMzOTcsImV4cCI6MjA2NDU3OTM5N30.K4se7kNbnAzGBbMqcoRei3bo2-9ag5bWJBHOQ1hLs5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);